services:
  # Serviço Principal
  app:
    container_name: agenda-api
    build:
      context: .
      dockerfile: Dockerfile
    image: agenda-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - localstack

  # Serviço MySQL
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-agenda
    environment:
      - MYSQL_DATABASE=vaga_liberada_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Serviço LocalStack (AWS Mock)
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-agenda
    ports:
      - "4566:4566"            # Gateway Edge Port
      - "4510-4559:4510-4559"  # Faixa de portas para serviços externos
    environment:
      - SERVICES=sqs,sns       # Habilita apenas o necessário
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      # Mapeia o script para rodar quando o LocalStack estiver "Ready"
      # - ./docker/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - "/var/run/docker.sock:/var/run/docker.sock"